name: home
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  extensions_library:
    path: ../../extensions_library
  form_repository:
    path: ../../form_repository
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
