name: flutter_dynamic_forms
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: 8.0.0
  flex_color_scheme: ^7.2.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  home:
    path: packages/features/home
  extensions_library:
    path: packages/extensions_library
  form_repository:
    path: packages/form_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
